### ISSUE TITLE
altLabel als Titel

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-lodview#2]
Es wird das altLabel als Titel angezeigt, obwohl ein reguläres Label vorhanden ist. Bsp. bb/StorageAreaNetwork

**Comment by KonradHoeffner** [comment]
[bb:StorageAreaNetwork](https://www.snik.eu/ontology/bb/StorageAreaNetwork) wird bei mir korrekt angezeigt, daher schließe ich die Issue. Falls sie bei dir immer noch auftritt, bitte wieder öffnen.
